import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from 'react-hot-toast';
import { createThirdwebClient } from "thirdweb";
import { ThirdwebProvider, ConnectButton } from "thirdweb/react";

const inter = Inter({ subsets: ['latin'] });

export const client = createThirdwebClient({ clientId: "958c572f0c8227579ffcc7708353af98" });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="block min-h-screen max-w-full bg-black">
          <ThirdwebProvider>
            <ConnectButton client={client} />
              {children}
          </ThirdwebProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
